### ISSUE TITLE
Getting too low level of randomness with LCGRandom

### ISSUE THREAD

**Issue by renatoathaydes** [jvasileff/ceylon-random#5]
I have some tests that require the generation of random Strings. I wrote it based on `Random.elements( characters ).take(n);`.

My test fails quite frequently now... I was using my own poor implementation of random before and it actually never failed.

If the randomness is good, I would expect duplicate Strings only every several billion Strings, but I am using only 100 Strings.

Could you confirm that this Random implementation has some kind of bias (maybe the default seed is very bad or something?).

Here's the implementation of `randomStrings()`:

https://github.com/renatoathaydes/specks/blob/master/source/com/athaydes/specks/generators.ceylon#L60

Thanks.

**Comment by jvasileff** [comment]
Sure, I'll take a look. In the mean time, you can also try the platform rng to rule in/out the generator itself - https://modules.ceylon-lang.org/repo/1/com/vasileff/ceylon/random/api/0.0.5/module-doc/api/index.html#platformRandom

**Comment by renatoathaydes** [comment]
Ah, that's pretty cool... I will try it!

**Comment by jvasileff** [comment]
@renatoathaydes the statistical tests still pass, and I'm not seeing any significant issues. Where exactly are you seeing the duplicates? Given that with the default values, `generateStrings` varies the output length uniformly from 0 to 99 characters, I would expect duplicates for short strings to happen fairly often.

Without doing any math, the output for

``` ceylon
    for (i in 0:100) {
        print(frequencies(generateStrings()).filter((entry) => entry.item > 1));
    }
```

looks reasonable to me, with a fairly common occurrence of multiple 0-length strings.

And this also looks reasonable, with several one and two length duplicates:

``` ceylon
    for (i in 0:10k) {
        value nonEmptyStrings
            = frequencies(generateStrings())
                .filter((entry) => entry.item > 1)
                .map(Entry.key).filter(not("".equals));

        if (!nonEmptyStrings.empty) {
            print(nonEmptyStrings);
        }
    }
```

**Comment by renatoathaydes** [comment]
With the platform-specific Random, the test passes every time.

Because the length is also randomly chosen, it shouldn't happen often that you get two Strings of similar length.

This may be the problem but I find it strange that the other 2 implementations of Random I tried always succeed.

**Comment by jvasileff** [comment]
Yes, that is strange for the implementation to matter. But you'll have to let me what sort of call to `generateStrings()` is causing problems for me to take a close look.

As for the length, you will almost _always_ get strings of the same length for 100 samples of 100 random lengths.

**Comment by jvasileff** [comment]
BTW, if the problem you are seeing is duplicate results for _consecutive_ calls to `generateStrings()`, especially on JS, the fix is to create an `LCGRandom()` in the calling function, and use the same one for each call to `generateStrings()`.

The reason for this is that the seed is based on millis + nanos, which isn't always a great source of unique numbers on JS.

**Comment by renatoathaydes** [comment]
You just found the problem, I believe :)

Anyway, what I had said about length, is that you need both length and contents to be the same to get a duplicate, which is really unlikely, I would think... but of course, there will be Strings with the same length...

**Comment by renatoathaydes** [comment]
I mentioned your library in the docs of https://github.com/renatoathaydes/specks
as I use it to create random test input.

Thanks!

**Comment by jvasileff** [comment]
> both length and contents to be the same

yes, but for zero-length strings, the contents will always be the same

> I mentioned your library

thanks, and congrats on the release!
